name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '00 00 * * *'
      
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
     - name: 'Checkout codes'
       uses: actions/checkout@v2
       
     - name: 'setup python'
       uses: actions/setup-python@master
       with: 
         python-version: 3.7
     
     - name: requirements
       run : pip3 install -r requirements.txt
       
     - name: main
       env:
          douyucookie: ${{ secrets.douyucookie }}
          list: ${{ secrets.list }}
          num: ${{ secrets.num }}
          sum: ${{ secrets.sum }}
       run:
          python3 test.py
